#!/bin/bash

if [ -f "composer.json" ]; then
    composer install --no-interaction --no-ansi --no-progress --optimize-autoloader

    composer run-script post-autoload-dump --no-interaction --no-ansi --no-progress
    composer run-script post-update-cmd --no-interaction --no-ansi --no-progress
    composer run-script post-root-package-install --no-interaction --no-ansi --no-progress
fi

if [ -f "package.json" ]; then

    npm install

    npm run build
fi
